# Tirana City Portrait
_Ongoing work_

- ...
- ...
- ...

<br><br>

# Tirana City Portrait

## MⅢ. 3. Archival Data

Structured archival table with MkDocs-safe rendering, optional OSM mapping helpers, and MapLibre layer preparation.

In [1]:
import json
import pandas as pd
from IPython.display import display, HTML

In [2]:
rows = [
    [
        "Historic Ottoman Tirana core",
        "pre-1920 → early 20th c.",
        ["Pazari i Ri", "Et'hem Bey Mosque surroundings", "Rruga Barrikadave"],
        ["Courtyard houses", "Bazaar fabric", "Small plot mixed-use", "Commercial strips"],
        ["Ottoman urban structure", "Tirana becomes capital (1920)"],
        []
    ],
    [
        "Monarchy-era planned capital",
        "1920–1940",
        ["Skanderbeg Square", "Boulevard Zogu I", "Boulevard Dëshmorët e Kombit"],
        ["Institutional ensembles", "Axial boulevards", "Perimeter blocks (neoclassical/rationalist)"],
        ["Capital formation", "Monarchy period", "Westernization"],
        ["Italian architects", "Austrian architects"]
    ],
    [
        "Socialist centre zone",
        "1945–1991",
        ["Boulevard Dëshmorët e Kombit", "Skanderbeg Square radial axes"],
        ["Monumental civic complexes", "Palace of Culture", "National Historical Museum", "Large plazas"],
        ["Communist takeover (1945)", "Socialist restructuring", "Regime change (1991)"],
        ["State planning institutes"]
    ],
    [
        "Socialist housing estates",
        "1945–1991",
        ["Rruga e Kavajës", "Rruga e Durrësit", "Rruga Myslym Shyri"],
        ["Prefabricated blocks (4–6 floors)", "Superblocks", "Slab buildings", "Internal green/open space"],
        ["State socialism", "Social housing provision", "Abolition of private property"],
        ["State design institutes"]
    ],
    [
        "Soviet-model block neighborhoods",
        "1945–1991",
        ["Hierarchical street networks", "Main vs internal roads"],
        ["Semi-perimeter blocks", "Freestanding slabs", "Large courtyards (later infill)"],
        ["Centralized planning", "Post-socialist fragmentation"],
        ["State planning bodies"]
    ],
    [
        "Inner-city densified blocks",
        "1992–2015",
        ["Rruga Myslym Shyri", "Rruga e Kavajës", "Rruga e Durrësit"],
        ["Block extensions", "Infill buildings", "Mixed-use ground floors", "Fragmented morphology"],
        ["Internal migration", "Privatization", "Weak planning control"],
        ["Private developers", "Informal actors"]
    ],
    [
        "Shallvaret",
        "pre-1991 → post-1991 transformation",
        ["Rruga Ibrahim Rugova", "Boulevard Bajram Curri"],
        ["Mid/high-rise blocks (>6 floors)", "Dense mixed-use", "Active frontage", "Café/retail dominance"],
        ["Post-socialist densification", "Commercial growth"],
        ["Private developers"]
    ],
    [
        "Kombinati",
        "socialist → post-1991",
        ["Rruga e Kavajës", "Industrial access roads"],
        ["Worker housing (2–5 floors)", "Textile factories", "Warehouses", "Adaptive reuse"],
        ["Industrialization", "Post-socialist decline", "Reuse"],
        ["State industry → private sector"]
    ],
    [
        "Industrial sites (within Tirana)",
        "1945–1991 → reuse after 1991",
        ["Western & southern industrial axes"],
        ["Industrial halls", "Factory compounds", "Converted warehouses", "Hybrid reuse"],
        ["Socialist industrial planning", "Market transition"],
        ["State → private"]
    ],
    [
        "Urban edges / peripheral expansion",
        "1992–2015",
        ["Radial roads (Durrës, Elbasan)"],
        ["Informal housing clusters", "Self-built multi-storey", "Irregular parcels"],
        ["Mass migration", "Uncontrolled expansion"],
        ["Informal builders"]
    ],
    [
        "Informal settlements",
        "1992–2015",
        ["Non-aligned / organic networks"],
        ["Incremental housing", "Mixed typologies", "High variability"],
        ["Collapse of state control", "Legalization processes"],
        ["Informal actors"]
    ],
]

In [3]:
df = pd.DataFrame(rows, columns=[
    "Area / Neighborhood",
    "Period of Evolution",
    "Streets / Axes",
    "Building Complexes",
    "Socio-Political Events",
    "Actors"
])

In [4]:
def to_bullets(lst):
    if not lst:
        return "—"
    return "<br>".join([f"– {x}" for x in lst])

In [5]:
df_display = df.copy()

for col in [
    "Streets / Axes",
    "Building Complexes",
    "Socio-Political Events",
    "Actors"
]:
    df_display[col] = df_display[col].apply(to_bullets)

In [6]:
html = df_display.to_html(escape=False, index=False)

styled_html = f"""
<style>
table {{
    width: 100%;
    border-collapse: collapse;
    font-size: 0.95rem;
}}

th, td {{
    text-align: left !important;
    vertical-align: top !important;
    padding: 8px 10px;
    border: 1px solid #ddd;
}}

th {{
    background-color: #f5f5f5;
}}
</style>
{html}
"""

display(HTML(styled_html))

## Optional: OSM mapping helpers

These cells extend the archival categories into simple OSM-oriented lookups.

In [7]:
osm_mapping = {
    "Courtyard houses": {"building": "residential"},
    "Bazaar fabric": {"landuse": "commercial"},
    "Small plot mixed-use": {"building": "mixed_use"},
    "Commercial strips": {"shop": "*"},
    "Institutional ensembles": {"building": "government"},
    "Perimeter blocks (neoclassical/rationalist)": {"building": "residential"},
    "Monumental civic complexes": {"building": "public"},
    "Palace of Culture": {"building": "civic"},
    "National Historical Museum": {"tourism": "museum"},
    "Prefabricated blocks (4–6 floors)": {"building": "apartments"},
    "Superblocks": {"landuse": "residential"},
    "Slab buildings": {"building": "apartments"},
    "Semi-perimeter blocks": {"building": "apartments"},
    "Freestanding slabs": {"building": "apartments"},
    "Block extensions": {"building": "residential"},
    "Infill buildings": {"building": "residential"},
    "Mixed-use ground floors": {"building": "mixed_use"},
    "Mid/high-rise blocks (>6 floors)": {"building": "apartments"},
    "Worker housing (2–5 floors)": {"building": "apartments"},
    "Textile factories": {"building": "industrial"},
    "Warehouses": {"building": "warehouse"},
    "Industrial halls": {"building": "industrial"},
    "Informal housing clusters": {"building": "residential"},
    "Self-built multi-storey": {"building": "residential"},
    "Incremental housing": {"building": "residential"}
}

In [8]:
def map_osm_tags(typologies):
    tags = []
    for t in typologies:
        if t in osm_mapping:
            tags.append(osm_mapping[t])
    return tags

df["OSM Tags"] = df["Building Complexes"].apply(map_osm_tags)
df[["Area / Neighborhood", "Building Complexes", "OSM Tags"]]

,Area / Neighborhood,Building Complexes,OSM Tags
0,Historic Ottoman Tirana core,"[Courtyard houses, Bazaar fabric, Small plot m...","[{'building': 'residential'}, {'landuse': 'com..."
1,Monarchy-era planned capital,"[Institutional ensembles, Axial boulevards, Pe...","[{'building': 'government'}, {'building': 'res..."
2,Socialist centre zone,"[Monumental civic complexes, Palace of Culture...","[{'building': 'public'}, {'building': 'civic'}..."
3,Socialist housing estates,"[Prefabricated blocks (4–6 floors), Superblock...","[{'building': 'apartments'}, {'landuse': 'resi..."
4,Soviet-model block neighborhoods,"[Semi-perimeter blocks, Freestanding slabs, La...","[{'building': 'apartments'}, {'building': 'apa..."
5,Inner-city densified blocks,"[Block extensions, Infill buildings, Mixed-use...","[{'building': 'residential'}, {'building': 're..."
6,Shallvaret,"[Mid/high-rise blocks (>6 floors), Dense mixed...",[{'building': 'apartments'}]
7,Kombinati,"[Worker housing (2–5 floors), Textile factorie...","[{'building': 'apartments'}, {'building': 'ind..."
8,Industrial sites (within Tirana),"[Industrial halls, Factory compounds, Converte...",[{'building': 'industrial'}]
9,Urban edges / peripheral expansion,"[Informal housing clusters, Self-built multi-s...","[{'building': 'residential'}, {'building': 're..."
10,Informal settlements,"[Incremental housing, Mixed typologies, High v...",[{'building': 'residential'}]

In [9]:
def format_osm_tags(tags):
    if not tags:
        return "—"
    parts = []
    for tag_dict in tags:
        for k, v in tag_dict.items():
            if v == "*":
                parts.append(f"{k}=*")
            else:
                parts.append(f"{k}={v}")
    return "<br>".join([f"– {p}" for p in parts])

df_osm_display = df.copy()
df_osm_display["Building Complexes"] = df_osm_display["Building Complexes"].apply(to_bullets)
df_osm_display["OSM Tags"] = df_osm_display["OSM Tags"].apply(format_osm_tags)

html = df_osm_display[[
    "Area / Neighborhood",
    "Building Complexes",
    "OSM Tags"
]].to_html(escape=False, index=False)

display(HTML(html))

In [10]:
def generate_overpass_query(tags, area="Tirana"):
    queries = []
    for tag_dict in tags:
        for k, v in tag_dict.items():
            if v == "*":
                queries.append(f'node["{k}"]')
                queries.append(f'way["{k}"]')
            else:
                queries.append(f'node["{k}"="{v}"]')
                queries.append(f'way["{k}"="{v}"]')

    query_body = "\n  ".join(queries)
    return f"""
[out:json][timeout:25];
area[\"name\"=\"{area}\"]->.searchArea;
(
  {query_body}
);
out body;
>;
out skel qt;
"""

df["Overpass Query"] = df["OSM Tags"].apply(generate_overpass_query)
df[["Area / Neighborhood", "Overpass Query"]].head(3)

,Area / Neighborhood,Overpass Query
0,Historic Ottoman Tirana core,"\n[out:json][timeout:25];\narea[""name""=""Tirana..."
1,Monarchy-era planned capital,"\n[out:json][timeout:25];\narea[""name""=""Tirana..."
2,Socialist centre zone,"\n[out:json][timeout:25];\narea[""name""=""Tirana..."

In [11]:
df[["Area / Neighborhood", "Overpass Query"]].to_csv(
    "tirana_overpass_queries.csv", index=False
)

## Optional: MapLibre layer preparation

These cells create simple category, color, and export helpers for use in a web map.

In [12]:
df["Map Category"] = [
    "historic_core",
    "planned_capital",
    "socialist_centre",
    "socialist_housing",
    "socialist_blocks",
    "post_socialist_densification",
    "post_socialist_densification",
    "industrial_socialist",
    "industrial_socialist",
    "peripheral_expansion",
    "informal_settlements"
]

df[["Area / Neighborhood", "Map Category"]]

                   Area / Neighborhood                  Map Category
0         Historic Ottoman Tirana core                 historic_core
1         Monarchy-era planned capital               planned_capital
2                Socialist centre zone              socialist_centre
3            Socialist housing estates             socialist_housing
4     Soviet-model block neighborhoods              socialist_blocks
5          Inner-city densified blocks  post_socialist_densification
6                           Shallvaret  post_socialist_densification
7                            Kombinati          industrial_socialist
8     Industrial sites (within Tirana)          industrial_socialist
9   Urban edges / peripheral expansion          peripheral_expansion
10                Informal settlements          informal_settlements

In [13]:
category_colors = {
    "historic_core": "#8c510a",
    "planned_capital": "#bf812d",
    "socialist_centre": "#01665e",
    "socialist_housing": "#35978f",
    "socialist_blocks": "#80cdc1",
    "post_socialist_densification": "#c51b7d",
    "industrial_socialist": "#5e3c99",
    "peripheral_expansion": "#fdae61",
    "informal_settlements": "#d73027",
}

df["Map Color"] = df["Map Category"].map(category_colors)
df[["Area / Neighborhood", "Map Category", "Map Color"]]

                   Area / Neighborhood                  Map Category Map Color
0         Historic Ottoman Tirana core                 historic_core   #8c510a
1         Monarchy-era planned capital               planned_capital   #bf812d
2                Socialist centre zone              socialist_centre   #01665e
3            Socialist housing estates             socialist_housing   #35978f
4     Soviet-model block neighborhoods              socialist_blocks   #80cdc1
5          Inner-city densified blocks  post_socialist_densification   #c51b7d
6                           Shallvaret  post_socialist_densification   #c51b7d
7                            Kombinati          industrial_socialist   #5e3c99
8     Industrial sites (within Tirana)          industrial_socialist   #5e3c99
9   Urban edges / peripheral expansion          peripheral_expansion   #fdae61
10                Informal settlements          informal_settlements   #d73027

In [14]:
map_config = df[[
    "Area / Neighborhood",
    "Period of Evolution",
    "Map Category",
    "Map Color",
    "Streets / Axes",
    "Building Complexes",
    "Socio-Political Events",
    "Actors"
]].copy()

map_config.to_json(
    "tirana_archival_map_config.json",
    orient="records",
    force_ascii=False,
    indent=2
)

map_config.head()

,Area / Neighborhood,Period of Evolution,Map Category,Map Color,Streets / Axes,Building Complexes,Socio-Political Events,Actors
0,Historic Ottoman Tirana core,pre-1920 → early 20th c.,historic_core,#8c510a,"[Pazari i Ri, Et'hem Bey Mosque surroundings, ...","[Courtyard houses, Bazaar fabric, Small plot m...","[Ottoman urban structure, Tirana becomes capit...",[]
1,Monarchy-era planned capital,1920–1940,planned_capital,#bf812d,"[Skanderbeg Square, Boulevard Zogu I, Boulevar...","[Institutional ensembles, Axial boulevards, Pe...","[Capital formation, Monarchy period, Westerniz...","[Italian architects, Austrian architects]"
2,Socialist centre zone,1945–1991,socialist_centre,#01665e,"[Boulevard Dëshmorët e Kombit, Skanderbeg Squa...","[Monumental civic complexes, Palace of Culture...","[Communist takeover (1945), Socialist restruct...",[State planning institutes]
3,Socialist housing estates,1945–1991,socialist_housing,#35978f,"[Rruga e Kavajës, Rruga e Durrësit, Rruga Mysl...","[Prefabricated blocks (4–6 floors), Superblock...","[State socialism, Social housing provision, Ab...",[State design institutes]
4,Soviet-model block neighborhoods,1945–1991,socialist_blocks,#80cdc1,"[Hierarchical street networks, Main vs interna...","[Semi-perimeter blocks, Freestanding slabs, La...","[Centralized planning, Post-socialist fragment...",[State planning bodies]

In [15]:
features = []

for _, row in df.iterrows():
    features.append({
        "type": "Feature",
        "geometry": None,
        "properties": {
            "name": row["Area / Neighborhood"],
            "period": row["Period of Evolution"],
            "category": row["Map Category"],
            "color": row["Map Color"],
            "streets": row["Streets / Axes"],
            "building_complexes": row["Building Complexes"],
            "events": row["Socio-Political Events"],
            "actors": row["Actors"],
        }
    })

geojson_placeholder = {
    "type": "FeatureCollection",
    "features": features
}

with open("tirana_archival_areas_placeholder.geojson", "w", encoding="utf-8") as f:
    json.dump(geojson_placeholder, f, ensure_ascii=False, indent=2)

geojson_placeholder["features"][:2]

[{'type': 'Feature',
  'geometry': None,
  'properties': {'name': 'Historic Ottoman Tirana core',
   'period': 'pre-1920 → early 20th c.',
   'category': 'historic_core',
   'color': '#8c510a',
   'streets': ['Pazari i Ri',
    "Et'hem Bey Mosque surroundings",
    'Rruga Barrikadave'],
   'building_complexes': ['Courtyard houses',
    'Bazaar fabric',
    'Small plot mixed-use',
    'Commercial strips'],
   'events': ['Ottoman urban structure', 'Tirana becomes capital (1920)'],
   'actors': []}},
 {'type': 'Feature',
  'geometry': None,
  'properties': {'name': 'Monarchy-era planned capital',
   'period': '1920–1940',
   'category': 'planned_capital',
   'color': '#bf812d',
   'streets': ['Skanderbeg Square',
    'Boulevard Zogu I',
    'Boulevard Dëshmorët e Kombit'],
   'building_complexes': ['Institutional ensembles',
    'Axial boulevards',
    'Perimeter blocks (neoclassical/rationalist)'],
   'events': ['Capital formation', 'Monarchy period', 'Westernization'],
   'actors': ['Italian architects', 'Austrian architects']}}]

In [16]:
demo_coords = {
    "Historic Ottoman Tirana core": (19.8187, 41.3275),
    "Monarchy-era planned capital": (19.8196, 41.3288),
    "Socialist centre zone": (19.8189, 41.3279),
    "Socialist housing estates": (19.8045, 41.3235),
    "Soviet-model block neighborhoods": (19.8065, 41.3240),
    "Inner-city densified blocks": (19.8145, 41.3215),
    "Shallvaret": (19.8118, 41.3230),
    "Kombinati": (19.7905, 41.3105),
    "Industrial sites (within Tirana)": (19.7925, 41.3120),
    "Urban edges / peripheral expansion": (19.8500, 41.3450),
    "Informal settlements": (19.8450, 41.3400),
}

In [17]:
from IPython.display import display
display(m)

NameError: name 'm' is not defined

In [ ]:
import folium

m = folium.Map(location=[41.3275, 19.8187], zoom_start=12)

for _, row in df.iterrows():
    if row["Area / Neighborhood"] in demo_coords:
        lon, lat = demo_coords[row["Area / Neighborhood"]]
        popup = f"""
        <b>{row['Area / Neighborhood']}</b><br>
        Period: {row['Period of Evolution']}<br>
        Category: {row.get('Map Category', '—')}
        """
        folium.Marker(
            location=[lat, lon],
            popup=popup
        ).add_to(m)

from IPython.display import display
display(m)

m.save("map.html")

## Optional: MapLibre example snippet

Use this JavaScript in your frontend after the map loads.

In [ ]:
maplibre_example = """
map.on(\"load\", async () => {
  const response = await fetch(\"./tirana_archival_areas_placeholder.geojson\");
  const archivalAreas = await response.json();

  map.addSource(\"archival-areas\", {
    type: \"geojson\",
    data: archivalAreas
  });

  map.addLayer({
    id: \"archival-areas-fill\",
    type: \"fill\",
    source: \"archival-areas\",
    paint: {
      \"fill-color\": [\"get\", \"color\"],
      \"fill-opacity\": 0.35
    }
  });

  map.addLayer({
    id: \"archival-areas-outline\",
    type: \"line\",
    source: \"archival-areas\",
    paint: {
      \"line-color\": [\"get\", \"color\"],
      \"line-width\": 2
    }
  });

  map.on(\"click\", \"archival-areas-fill\", (e) => {
    const props = e.features[0].properties;

    const html = `
      <h3>${props.name}</h3>
      <p><strong>Period:</strong> ${props.period}</p>
      <p><strong>Category:</strong> ${props.category}</p>
    `;

    new maplibregl.Popup()
      .setLngLat(e.lngLat)
      .setHTML(html)
      .addTo(map);
  });
});
"""

print(maplibre_example)

map.on("load", async () => {
  const response = await fetch("./tirana_archival_areas_placeholder.geojson");
  const archivalAreas = await response.json();

  map.addSource("archival-areas", {
    type: "geojson",
    data: archivalAreas
  });

  map.addLayer({
    id: "archival-areas-fill",
    type: "fill",
    source: "archival-areas",
    paint: {
      "fill-color": ["get", "color"],
      "fill-opacity": 0.35
    }
  });

  map.addLayer({
    id: "archival-areas-outline",
    type: "line",
    source: "archival-areas",
    paint: {
      "line-color": ["get", "color"],
      "line-width": 2
    }
  });

  map.on("click", "archival-areas-fill", (e) => {
    const props = e.features[0].properties;

    const html = `
      <h3>${props.name}</h3>
      <p><strong>Period:</strong> ${props.period}</p>
      <p><strong>Category:</strong> ${props.category}</p>
    `;

    new maplibregl.Popup()
      .setLngLat(e.lngLat)
      .setHTML(html)
      .addTo(map);
  });
});

In [ ]:
import folium
from IPython.display import display

m = folium.Map(location=[41.3275, 19.8187], zoom_start=12)

folium.Marker(
    [41.3275, 19.8187],
    popup="Tirana center"
).add_to(m)

display(m)
m.save("map.html")

## 1. Base Map Layers

The different data sources used for the analysis are the following:

- OpenStreetMap
- Overture
- GDE

<br><br>

## 2. Statistical Layers

- Global Exposure Model
- GHSL: Algorithm: Shape to Point
- Census

## 3. Archival Data

Structured archival table with MkDocs-safe rendering and optional OSM mapping helpers.

In [ ]:
import pandas as pd
from IPython.display import display, HTML

In [ ]:
rows = [
    [
        "Historic Ottoman Tirana core",
        "pre-1920 → early 20th c.",
        ["Pazari i Ri", "Et'hem Bey Mosque surroundings", "Rruga Barrikadave"],
        ["Courtyard houses", "Bazaar fabric", "Small plot mixed-use", "Commercial strips"],
        ["Ottoman urban structure", "Tirana becomes capital (1920)"],
        []
    ],
    [
        "Monarchy-era planned capital",
        "1920–1940",
        ["Skanderbeg Square", "Boulevard Zogu I", "Boulevard Dëshmorët e Kombit"],
        ["Institutional ensembles", "Axial boulevards", "Perimeter blocks (neoclassical/rationalist)"],
        ["Capital formation", "Monarchy period", "Westernization"],
        ["Italian architects", "Austrian architects"]
    ],
    [
        "Socialist centre zone",
        "1945–1991",
        ["Boulevard Dëshmorët e Kombit", "Skanderbeg Square radial axes"],
        ["Monumental civic complexes", "Palace of Culture", "National Historical Museum", "Large plazas"],
        ["Communist takeover (1945)", "Socialist restructuring", "Regime change (1991)"],
        ["State planning institutes"]
    ],
    [
        "Socialist housing estates",
        "1945–1991",
        ["Rruga e Kavajës", "Rruga e Durrësit", "Rruga Myslym Shyri"],
        ["Prefabricated blocks (4–6 floors)", "Superblocks", "Slab buildings", "Internal green/open space"],
        ["State socialism", "Social housing provision", "Abolition of private property"],
        ["State design institutes"]
    ],
    [
        "Soviet-model block neighborhoods",
        "1945–1991",
        ["Hierarchical street networks", "Main vs internal roads"],
        ["Semi-perimeter blocks", "Freestanding slabs", "Large courtyards (later infill)"],
        ["Centralized planning", "Post-socialist fragmentation"],
        ["State planning bodies"]
    ],
    [
        "Inner-city densified blocks",
        "1992–2015",
        ["Rruga Myslym Shyri", "Rruga e Kavajës", "Rruga e Durrësit"],
        ["Block extensions", "Infill buildings", "Mixed-use ground floors", "Fragmented morphology"],
        ["Internal migration", "Privatization", "Weak planning control"],
        ["Private developers", "Informal actors"]
    ],
    [
        "Shallvaret",
        "pre-1991 → post-1991 transformation",
        ["Rruga Ibrahim Rugova", "Boulevard Bajram Curri"],
        ["Mid/high-rise blocks (>6 floors)", "Dense mixed-use", "Active frontage", "Café/retail dominance"],
        ["Post-socialist densification", "Commercial growth"],
        ["Private developers"]
    ],
    [
        "Kombinati",
        "socialist → post-1991",
        ["Rruga e Kavajës", "Industrial access roads"],
        ["Worker housing (2–5 floors)", "Textile factories", "Warehouses", "Adaptive reuse"],
        ["Industrialization", "Post-socialist decline", "Reuse"],
        ["State industry → private sector"]
    ],
    [
        "Industrial sites (within Tirana)",
        "1945–1991 → reuse after 1991",
        ["Western & southern industrial axes"],
        ["Industrial halls", "Factory compounds", "Converted warehouses", "Hybrid reuse"],
        ["Socialist industrial planning", "Market transition"],
        ["State → private"]
    ],
    [
        "Urban edges / peripheral expansion",
        "1992–2015",
        ["Radial roads (Durrës, Elbasan)"],
        ["Informal housing clusters", "Self-built multi-storey", "Irregular parcels"],
        ["Mass migration", "Uncontrolled expansion"],
        ["Informal builders"]
    ],
    [
        "Informal settlements",
        "1992–2015",
        ["Non-aligned / organic networks"],
        ["Incremental housing", "Mixed typologies", "High variability"],
        ["Collapse of state control", "Legalization processes"],
        ["Informal actors"]
    ],
]

In [ ]:
df = pd.DataFrame(rows, columns=[
    "Area / Neighborhood",
    "Period of Evolution",
    "Streets / Axes",
    "Building Complexes",
    "Socio-Political Events",
    "Actors"
])
df

,Area / Neighborhood,Period of Evolution,Streets / Axes,Building Complexes,Socio-Political Events,Actors
0,Historic Ottoman Tirana core,pre-1920 → early 20th c.,"[Pazari i Ri, Et'hem Bey Mosque surroundings, ...","[Courtyard houses, Bazaar fabric, Small plot m...","[Ottoman urban structure, Tirana becomes capit...",[]
1,Monarchy-era planned capital,1920–1940,"[Skanderbeg Square, Boulevard Zogu I, Boulevar...","[Institutional ensembles, Axial boulevards, Pe...","[Capital formation, Monarchy period, Westerniz...","[Italian architects, Austrian architects]"
2,Socialist centre zone,1945–1991,"[Boulevard Dëshmorët e Kombit, Skanderbeg Squa...","[Monumental civic complexes, Palace of Culture...","[Communist takeover (1945), Socialist restruct...",[State planning institutes]
3,Socialist housing estates,1945–1991,"[Rruga e Kavajës, Rruga e Durrësit, Rruga Mysl...","[Prefabricated blocks (4–6 floors), Superblock...","[State socialism, Social housing provision, Ab...",[State design institutes]
4,Soviet-model block neighborhoods,1945–1991,"[Hierarchical street networks, Main vs interna...","[Semi-perimeter blocks, Freestanding slabs, La...","[Centralized planning, Post-socialist fragment...",[State planning bodies]
5,Inner-city densified blocks,1992–2015,"[Rruga Myslym Shyri, Rruga e Kavajës, Rruga e ...","[Block extensions, Infill buildings, Mixed-use...","[Internal migration, Privatization, Weak plann...","[Private developers, Informal actors]"
6,Shallvaret,pre-1991 → post-1991 transformation,"[Rruga Ibrahim Rugova, Boulevard Bajram Curri]","[Mid/high-rise blocks (>6 floors), Dense mixed...","[Post-socialist densification, Commercial growth]",[Private developers]
7,Kombinati,socialist → post-1991,"[Rruga e Kavajës, Industrial access roads]","[Worker housing (2–5 floors), Textile factorie...","[Industrialization, Post-socialist decline, Re...",[State industry → private sector]
8,Industrial sites (within Tirana),1945–1991 → reuse after 1991,[Western & southern industrial axes],"[Industrial halls, Factory compounds, Converte...","[Socialist industrial planning, Market transit...",[State → private]
9,Urban edges / peripheral expansion,1992–2015,"[Radial roads (Durrës, Elbasan)]","[Informal housing clusters, Self-built multi-s...","[Mass migration, Uncontrolled expansion]",[Informal builders]
10,Informal settlements,1992–2015,[Non-aligned / organic networks],"[Incremental housing, Mixed typologies, High v...","[Collapse of state control, Legalization proce...",[Informal actors]

In [ ]:
def to_bullets(lst):
    if not lst:
        return "—"
    return "<br>".join([f"– {x}" for x in lst])

In [ ]:
df_display = df.copy()

for col in [
    "Streets / Axes",
    "Building Complexes",
    "Socio-Political Events",
    "Actors"
]:
    df_display[col] = df_display[col].apply(to_bullets)

In [ ]:
from IPython.display import HTML, display

styled_html = """
<style>
table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.95rem;
}

th, td {
    text-align: left !important;
    vertical-align: top !important;
    padding: 8px 10px;
    border: 1px solid #ddd;
}

th {
    background-color: #f5f5f5;
}
</style>
""" + html

display(HTML(styled_html))

## OSM mapping helpers

These cells extend the archival categories into simple OSM-oriented lookups.

In [ ]:
osm_mapping = {
    "Courtyard houses": {"building": "residential"},
    "Bazaar fabric": {"landuse": "commercial"},
    "Small plot mixed-use": {"building": "mixed_use"},
    "Commercial strips": {"shop": "*"},
    "Institutional ensembles": {"building": "government"},
    "Perimeter blocks (neoclassical/rationalist)": {"building": "residential"},
    "Monumental civic complexes": {"building": "public"},
    "Palace of Culture": {"building": "civic"},
    "National Historical Museum": {"tourism": "museum"},
    "Prefabricated blocks (4–6 floors)": {"building": "apartments"},
    "Superblocks": {"landuse": "residential"},
    "Slab buildings": {"building": "apartments"},
    "Semi-perimeter blocks": {"building": "apartments"},
    "Freestanding slabs": {"building": "apartments"},
    "Block extensions": {"building": "residential"},
    "Infill buildings": {"building": "residential"},
    "Mixed-use ground floors": {"building": "mixed_use"},
    "Mid/high-rise blocks (>6 floors)": {"building": "apartments"},
    "Worker housing (2–5 floors)": {"building": "apartments"},
    "Textile factories": {"building": "industrial"},
    "Warehouses": {"building": "warehouse"},
    "Industrial halls": {"building": "industrial"},
    "Informal housing clusters": {"building": "residential"},
    "Self-built multi-storey": {"building": "residential"},
    "Incremental housing": {"building": "residential"}
}

In [ ]:
def map_osm_tags(typologies):
    tags = []
    for t in typologies:
        if t in osm_mapping:
            tags.append(osm_mapping[t])
    return tags

df["OSM Tags"] = df["Building Complexes"].apply(map_osm_tags)
df[["Area / Neighborhood", "Building Complexes", "OSM Tags"]]

,Area / Neighborhood,Building Complexes,OSM Tags
0,Historic Ottoman Tirana core,"[Courtyard houses, Bazaar fabric, Small plot m...","[{'building': 'residential'}, {'landuse': 'com..."
1,Monarchy-era planned capital,"[Institutional ensembles, Axial boulevards, Pe...","[{'building': 'government'}, {'building': 'res..."
2,Socialist centre zone,"[Monumental civic complexes, Palace of Culture...","[{'building': 'public'}, {'building': 'civic'}..."
3,Socialist housing estates,"[Prefabricated blocks (4–6 floors), Superblock...","[{'building': 'apartments'}, {'landuse': 'resi..."
4,Soviet-model block neighborhoods,"[Semi-perimeter blocks, Freestanding slabs, La...","[{'building': 'apartments'}, {'building': 'apa..."
5,Inner-city densified blocks,"[Block extensions, Infill buildings, Mixed-use...","[{'building': 'residential'}, {'building': 're..."
6,Shallvaret,"[Mid/high-rise blocks (>6 floors), Dense mixed...",[{'building': 'apartments'}]
7,Kombinati,"[Worker housing (2–5 floors), Textile factorie...","[{'building': 'apartments'}, {'building': 'ind..."
8,Industrial sites (within Tirana),"[Industrial halls, Factory compounds, Converte...",[{'building': 'industrial'}]
9,Urban edges / peripheral expansion,"[Informal housing clusters, Self-built multi-s...","[{'building': 'residential'}, {'building': 're..."
10,Informal settlements,"[Incremental housing, Mixed typologies, High v...",[{'building': 'residential'}]

In [ ]:
def generate_overpass_query(tags, area="Tirana"):
    queries = []
    for tag_dict in tags:
        for k, v in tag_dict.items():
            if v == "*":
                queries.append(f'node["{k}"]')
                queries.append(f'way["{k}"]')
            else:
                queries.append(f'node["{k}"="{v}"]')
                queries.append(f'way["{k}"="{v}"]')

    query_body = "\n  ".join(queries)
    return f"""
[out:json][timeout:25];
area[\"name\"=\"{area}\"]->.searchArea;
(
  {query_body}
);
out body;
>;
out skel qt;
"""

df["Overpass Query"] = df["OSM Tags"].apply(generate_overpass_query)
df[["Area / Neighborhood", "Overpass Query"]].head(3)

,Area / Neighborhood,Overpass Query
0,Historic Ottoman Tirana core,"\n[out:json][timeout:25];\narea[""name""=""Tirana..."
1,Monarchy-era planned capital,"\n[out:json][timeout:25];\narea[""name""=""Tirana..."
2,Socialist centre zone,"\n[out:json][timeout:25];\narea[""name""=""Tirana..."

In [ ]:
df[["Area / Neighborhood", "Overpass Query"]].to_csv(
    "tirana_overpass_queries.csv", index=False
)


<br><br>

## 3. Archival Data
This section summarizes key areas and neighborhood types in Tirana discussed in the archival and morphological literature, focusing on their period of evolution, identifiable streets or axes only where explicitly known, main building complexes, major socio-political shifts, and associated actors.

- Events
- Wikipedia
- World Imagery Wayback

In [ ]:
import pandas as pd
from IPython.display import display, HTML

In [ ]:
# build dataframe
df = pd.DataFrame(rows, columns=[
    "Area / Neighborhood",
    "Period of Evolution",
    "Streets / Axes",
    "Building Complexes",
    "Socio-Political Events",
    "Actors"
])

In [ ]:
def to_ul(items):
    if not items:
        return "—"
    return "<ul>" + "".join(f"<li>{item}</li>" for item in items) + "</ul>"

In [ ]:
df_display = df.copy()

for col in [
    "Streets / Axes",
    "Building Complexes",
    "Socio-Political Events",
    "Actors"
]:
    df_display[col] = df_display[col].apply(to_ul)

html = df_display.to_html(escape=False, index=False)

styled_html = f"""
<style>
table {{
    width: 100%;
    border-collapse: collapse;
    font-size: 0.95rem;
}}
th, td {{
    text-align: left !important;
    vertical-align: top !important;
    padding: 8px 10px;
    border: 1px solid #ddd;
}}
td ul {{
    margin: 0;
    padding-left: 1.2em;
}}
</style>
{html}
"""

from IPython.display import HTML, display

display(HTML(styled_html))

In [ ]:
import pandas as pd

rows = [
    [
        "Historic Ottoman Tirana core",
        "pre-1920 → early 20th c.",
        "• Pazari i Ri<br>• Et'hem Bey Mosque surroundings<br>• Rruga Barrikadave",
        "• Courtyard houses<br>• Bazaar fabric<br>• Small plot mixed-use<br>• Commercial strips",
        "• Ottoman urban structure<br>• Tirana becomes capital (1920)",
        "—"
    ],
    [
        "Monarchy-era planned capital",
        "1920–1940",
        "• Skanderbeg Square<br>• Boulevard Zogu I<br>• Boulevard Dëshmorët e Kombit",
        "• Institutional ensembles<br>• Axial boulevards<br>• Perimeter blocks (neoclassical/rationalist)",
        "• Capital formation<br>• Monarchy period<br>• Westernization",
        "• Italian architects<br>• Austrian architects"
    ],
    [
        "Socialist centre zone",
        "1945–1991",
        "• Boulevard Dëshmorët e Kombit<br>• Skanderbeg Square radial axes",
        "• Monumental civic complexes<br>• Palace of Culture<br>• National Historical Museum<br>• Large plazas",
        "• Communist takeover (1945)<br>• Socialist restructuring<br>• Regime change (1991)",
        "• State planning institutes"
    ],
    [
        "Socialist housing estates",
        "1945–1991",
        "• Rruga e Kavajës<br>• Rruga e Durrësit<br>• Rruga Myslym Shyri",
        "• Prefabricated blocks (4–6 floors)<br>• Superblocks<br>• Slab buildings<br>• Internal green/open space",
        "• State socialism<br>• Social housing provision<br>• Abolition of private property",
        "• State design institutes"
    ],
    [
        "Soviet-model block neighborhoods",
        "1945–1991",
        "• Hierarchical street networks<br>• Main vs internal roads",
        "• Semi-perimeter blocks<br>• Freestanding slabs<br>• Large courtyards (later infill)",
        "• Centralized planning<br>• Post-socialist fragmentation",
        "• State planning bodies"
    ],
    [
        "Inner-city densified blocks",
        "1992–2015",
        "• Rruga Myslym Shyri<br>• Rruga e Kavajës<br>• Rruga e Durrësit",
        "• Block extensions<br>• Infill buildings<br>• Mixed-use ground floors<br>• Fragmented morphology",
        "• Internal migration<br>• Privatization<br>• Weak planning control",
        "• Private developers<br>• Informal actors"
    ],
    [
        "Shallvaret",
        "pre-1991 → post-1991 transformation",
        "• Rruga Ibrahim Rugova<br>• Boulevard Bajram Curri",
        "• Mid/high-rise blocks (>6 floors)<br>• Dense mixed-use<br>• Active frontage<br>• Café/retail dominance",
        "• Post-socialist densification<br>• Commercial growth",
        "• Private developers"
    ],
    [
        "Kombinati",
        "socialist → post-1991",
        "• Rruga e Kavajës<br>• Industrial access roads",
        "• Worker housing (2–5 floors)<br>• Textile factories<br>• Warehouses<br>• Adaptive reuse",
        "• Industrialization<br>• Post-socialist decline<br>• Reuse",
        "• State industry → private sector"
    ],
    [
        "Industrial sites (within Tirana)",
        "1945–1991 → reuse after 1991",
        "• Western & southern industrial axes",
        "• Industrial halls<br>• Factory compounds<br>• Converted warehouses<br>• Hybrid reuse",
        "• Socialist industrial planning<br>• Market transition",
        "• State → private"
    ],
    [
        "Urban edges / peripheral expansion",
        "1992–2015",
        "• Radial roads (Durrës, Elbasan)",
        "• Informal housing clusters<br>• Self-built multi-storey<br>• Irregular parcels",
        "• Mass migration<br>• Uncontrolled expansion",
        "• Informal builders"
    ],
    [
        "Informal settlements",
        "1992–2015",
        "• Non-aligned / organic networks",
        "• Incremental housing<br>• Mixed typologies<br>• High variability",
        "• Collapse of state control<br>• Legalization processes",
        "• Informal actors"
    ],
]

df = pd.DataFrame(rows, columns=[
    "Area / Neighborhood",
    "Period of Evolution",
    "Streets / Axes",
    "Building Complexes",
    "Socio-Political Events",
    "Actors"
])

# df

In [ ]:
from IPython.display import display, HTML

html = df.to_html(escape=False)

styled_html = f"""
<style>
table {{
    width: 100%;
    border-collapse: collapse;
}}

th {{
    text-align: left !important;
}}

td {{
    text-align: left !important;
    vertical-align: top;
    padding: 6px;
}}

td ul {{
    margin: 0;
    padding-left: 18px;
}}

</style>
{html}
"""

display(HTML(styled_html))

In [ ]:
# from IPython.display import display

# display(df.style.set_properties(**{
#     'text-align': 'left'
# }).set_table_styles([
#     {'selector': 'th', 'props': [('text-align', 'left')]}
# ]))

<br><br>
## 4. Clustering 
- Rule based/event-based suggestions
- Algorithm: Spatial Interpolation

<br><br>

## 5. Building Stock Scenarios
- Algorithm: Filter based on archival data
- Redistribute